export enum OrderStatus {
    CREATED = 'CREATED',
    CANCELED = 'CANCELED',
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
}
