export enum OrderStatus {
    CREATED = 'CREATED',
    CANCELED = 'CANCELED',
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    PAYMENT_CONFIRMED = 'PAYMENT_CONFIRMED',
    PROCESSING = 'PROCESSING',
    SHIPPED = 'SHIPPED',
    DELIVERED = 'DELIVERED',
}

export enum ExceptionCode {
    PRODUCT_NOT_FOUND = 'PRODUCT_NOT_FOUND',
    INACTIVE_PRODUCT = 'INACTIVE_PRODUCT',
    UNAVAILABLE_QUANTITY_REQUESTED = 'UNAVAILABLE_QUANTITY_REQUESTED',
}
